using System.ComponentModel;

namespace FinanceProcessor.IEXSharp.Model.CoreData.StockResearch.Request
{
	public enum IndicatorName
	{
		[Description("abs")]
		Abs,
		[Description("acos")]
		Acos,
		[Description("ad")]
		Ad,
		[Description("add")]
		Add,
		[Description("adosc")]
		Adosc,
		[Description("adx")]
		Adx,
		[Description("adxr")]
		adxr,
		[Description("ao")]
		Ao,
		[Description("apo")]
		Apo,
		[Description("aroon")]
		Aroon,
		[Description("aroonosc")]
		Aroonosc,
		[Description("asin")]
		Asin,
		[Description("atan")]
		Atan,
		[Description("atr")]
		Atr,
		[Description("avgprice")]
		Avgprice,
		[Description("bbands")]
		Bbands,
		[Description("bop")]
		Bop,
		[Description("cci")]
		Cci,
		[Description("ceil")]
		Ceil,
		[Description("cmo")]
		Cmo,
		[Description("cos")]
		Cos,
		[Description("cosh")]
		Cosh,
		[Description("crossany")]
		Crossany,
		[Description("crossany")]
		Crossover,
		[Description("cvi")]
		Cvi,
		[Description("decay")]
		Decay,
		[Description("dema")]
		Dema,
		[Description("di")]
		Di,
		[Description("div")]
		Div,
		[Description("dm")]
		Dm,
		[Description("dpo")]
		Dpo,
		[Description("dx")]
		Dx,
		[Description("edecay")]
		Edecay,
		[Description("ema")]
		Ema,
		[Description("emv")]
		Emv,
		[Description("exp")]
		Exp,
		[Description("fisher")]
		Fisher,
		[Description("floor")]
		Floor,
		[Description("fosc")]
		Fosc,
		[Description("hma")]
		Hma,
		[Description("kama")]
		Kama,
		[Description("kvo")]
		Kvo,
		[Description("lag")]
		Lag,
		[Description("linreg")]
		Linreg,
		[Description("linregintercept")]
		Linregintercept,
		[Description("linregslope")]
		Linregslope,
		[Description("ln")]
		Ln,
		[Description("log10")]
		Log10,
		[Description("macd")]
		Macd,
		[Description("marketfi")]
		Marketfi,
		[Description("mass")]
		Mass,
		[Description("max")]
		Max,
		[Description("md")]
		Md,
		[Description("medprice")]
		Medprice,
		[Description("mfi")]
		Mfi,
		[Description("min")]
		Min,
		[Description("mom")]
		Mom,
		[Description("msw")]
		Msw,
		[Description("mul")]
		Mul,
		[Description("natr")]
		Natr,
		[Description("nvi")]
		Nvi,
		[Description("obv")]
		Obv,
		[Description("ppo")]
		Ppo,
		[Description("psar")]
		Psar,
		[Description("pvi")]
		Pvi,
		[Description("qstick")]
		Qstick,
		[Description("roc")]
		Roc,
		[Description("rocr")]
		Rocr,
		[Description("round")]
		Round,
		[Description("rsi")]
		Rsi,
		[Description("sin")]
		Sin,
		[Description("sinh")]
		Sinh,
		[Description("sma")]
		Sma,
		[Description("sqrt")]
		Sqrt,
		[Description("stddev")]
		Stddev,
		[Description("stderr")]
		Stderr,
		[Description("stoch")]
		Stoch,
		[Description("stochrsi")]
		Stochrsi,
		[Description("sub")]
		Sub,
		[Description("sum")]
		Sum,
		[Description("tan")]
		Tan,
		[Description("tanh")]
		Tanh,
		[Description("tema")]
		Tema,
		[Description("todeg")]
		Todeg,
		[Description("torad")]
		Torad,
		[Description("tr")]
		Tr,
		[Description("trima")]
		Trima,
		[Description("trix")]
		Trix,
		[Description("trunc")]
		Trunc,
		[Description("Tsf")]
		Tsf,
		[Description("typprice")]
		Typprice,
		[Description("ultosc")]
		Ultosc,
		[Description("var")]
		Var,
		[Description("vhf")]
		Vhf,
		[Description("vidya")]
		Vidya,
		[Description("volatility")]
		Volatility,
		[Description("vosc")]
		Vosc,
		[Description("vwma")]
		Vwma,
		[Description("wad")]
		Wad,
		[Description("wcprice")]
		Wcprice,
		[Description("wilders")]
		Wilders,
		[Description("willr")]
		Willr,
		[Description("wma")]
		Wma,
		[Description("zlema")]
		Zlema
	}
}
