namespace FinanceProcessor.IEXSharp.Model.CoreData.StockFundamentals.Response
{
	public class FundamentalValuationsResponse
	{
        public double accountsPayableTurnover { get; set; }
        public double accountsReceivableTurnover { get; set; }
        public double altmanZScore { get; set; }
        public string asOfDate { get; set; }
        public double assetsToEquity { get; set; }
        public double assetTurnover { get; set; }
        public string bbgCompositeTicker { get; set; }
        public double bookValuePerShare { get; set; }
        public double cashConversionCycle { get; set; }
        public string cik { get; set; }
        public string companyName { get; set; }
        public string companyStatusCurrent { get; set; }
        public double currentRatio { get; set; }
        public string dataGenerationDate { get; set; }
        public string dataType { get; set; }
        public double daysInAccountsPayable { get; set; }
        public double daysInInventory { get; set; }
        public double daysInRevenueDeferred { get; set; }
        public double daysRevenueOutstanding { get; set; }
        public double debtToAssets { get; set; }
        public double debtToCapitalization { get; set; }
        public double debtToEbitda { get; set; }
        public double debtToEquity { get; set; }
        public double dividendPerShare { get; set; }
        public double dividendYield { get; set; }
        public double earningsYield { get; set; }
        public double ebitdaGrowth { get; set; }
        public double ebitdaMargin { get; set; }
        public long ebitdaReported { get; set; }
        public double ebitGrowth { get; set; }
        public long ebitReported { get; set; }
        public double ebitToInterestExpense { get; set; }
        public double ebitToRevenue { get; set; }
        public long enterpriseValue { get; set; }
        public double evToEbit { get; set; }
        public double evToEbitda { get; set; }
        public double evToFcf { get; set; }
        public double evToInvestedCapital { get; set; }
        public double evToNopat { get; set; }
        public double evToOcf { get; set; }
        public double evToSales { get; set; }
        public long expenseOperating { get; set; }
        public double fcfYield { get; set; }
        public string figi { get; set; }
        public string filingDate { get; set; }
        public string filingType { get; set; }
        public long fiscalQuarter { get; set; }
        public long fiscalYear { get; set; }
        public double fixedAssetTurnover { get; set; }
        public double freeCashFlow { get; set; }
        public double freeCashFlowGrowth { get; set; }
        public double freeCashFlowToRevenue { get; set; }
        public long goodwillTotal { get; set; }
        public double incomeNetPerWabso { get; set; }
        public double incomeNetPerWabsoSplitAdjusted { get; set; }
        public double incomeNetPerWabsoSplitAdjustedYoyDeltaPercent { get; set; }
        public double incomeNetPerWadso { get; set; }
        public double incomeNetPerWadsoSplitAdjusted { get; set; }
        public double incomeNetPerWadsoSplitAdjustedYoyDeltaPercent { get; set; }
        public long incomeNetPreTax { get; set; }
        public double interestBurden { get; set; }
        public long interestMinority { get; set; }
        public double inventoryTurnover { get; set; }
        public long investedCapital { get; set; }
        public double investedCapitalGrowth { get; set; }
        public double investedCapitalTurnover { get; set; }
        public double leverage { get; set; }
        public long marketCapPeriodEnd { get; set; }
        public long netDebt { get; set; }
        public double netDebtToEbitda { get; set; }
        public double netIncomeGrowth { get; set; }
        public double netIncomeToRevenue { get; set; }
        public long netWorkingCapital { get; set; }
        public double netWorkingCapitalGrowth { get; set; }
        public double nibclRevenueDeferredTurnover { get; set; }
        public double nopat { get; set; }
        public double nopatGrowth { get; set; }
        public double nopatMargin { get; set; }
        public double operatingCashFlowGrowth { get; set; }
        public double operatingCashFlowInterestCoverage { get; set; }
        public double operatingCfToRevenue { get; set; }
        public long operatingIncome { get; set; }
        public double operatingIncomeToRevenue { get; set; }
        public double operatingReturnOnAssets { get; set; }
        public string periodEndDate { get; set; }
        public long ppAndENet { get; set; }
        public long preferredEquityToCapital { get; set; }
        public double pretaxIncomeMargin { get; set; }
        public double priceAccountingPeriodEnd { get; set; }
        public string priceDateAccountingPeriodEnd { get; set; }
        public double priceToRevenue { get; set; }
        public double profitGrossToRevenue { get; set; }
        public double pToBv { get; set; }
        public double pToE { get; set; }
        public double quickRatio { get; set; }
        public double researchDevelopmentToRevenue { get; set; }
        public double returnOnAssets { get; set; }
        public double returnOnEquity { get; set; }
        public double revenueGrowth { get; set; }
        public double roce { get; set; }
        public double roic { get; set; }
        public long scexhid { get; set; }
        public long secid { get; set; }
        public double sgaToRevenue { get; set; }
        public string stockExchange { get; set; }
        public string symbol { get; set; }
        public double taxBurden { get; set; }
        public string ticker { get; set; }
        public long totalCapital { get; set; }
        public long totalDebt { get; set; }
        public string updateReason { get; set; }
        public long wabso { get; set; }
        public long wabsoSplitAdjusted { get; set; }
        public long wadso { get; set; }
        public long wadsoSplitAdjusted { get; set; }
        public double workingCapitalTurnover { get; set; }
        public string id { get; set; }
        public string key { get; set; }
        public string subkey { get; set; }
        public long date { get; set; }
        public double updated { get; set; }
    }
}
