namespace FinanceProcessor.Core.Models
{
	public class AdvancedFundamentalsDto
    {
        public decimal? AccountsPayable { get; set; }
        public decimal? AccountsPayableTurnover { get; set; }
        public decimal? AccountsReceivable { get; set; }
        public decimal? AccountsReceivableTurnover { get; set; }
        public string AsOfDate { get; set; }
        public decimal? AssetsCurrentCash { get; set; }
        public decimal? AssetsCurrentCashRestricted { get; set; }
        public decimal? AssetsCurrentDeferredCompensation { get; set; }
        public decimal? AssetsCurrentDeferredTax { get; set; }
        public decimal? AssetsCurrentDiscontinuedOperations { get; set; }
        public decimal? AssetsCurrentInvestments { get; set; }
        public decimal? AssetsCurrentLeasesOperating { get; set; }
        public decimal? AssetsCurrentLoansNet { get; set; }
        public decimal? AssetsCurrentOther { get; set; }
        public decimal? AssetsCurrentSeparateAccounts { get; set; }
        public decimal? AssetsCurrentUnadjusted { get; set; }
        public decimal? AssetsFixed { get; set; }
        public decimal? AssetsFixedDeferredCompensation { get; set; }
        public decimal? AssetsFixedDeferredTax { get; set; }
        public decimal? AssetsFixedDiscontinuedOperations { get; set; }
        public decimal? AssetsFixedLeasesOperating { get; set; }
        public decimal? AssetsFixedOperatingDiscontinuedOperations { get; set; }
        public decimal? AssetsFixedOperatingSubsidiaryUnconsolidated { get; set; }
        public decimal? AssetsFixedOreo { get; set; }
        public decimal? AssetsFixedOther { get; set; }
        public decimal? AssetsFixedUnconsolidated { get; set; }
        public decimal? AssetsUnadjusted { get; set; }
        public decimal? Capex { get; set; }
        public decimal? CapexAcquisition { get; set; }
        public decimal? CapexMaintenance { get; set; }
        public decimal? CashConversionCycle { get; set; }
        public decimal? CashFlowFinancing { get; set; }
        public decimal? CashFlowInvesting { get; set; }
        public decimal? CashFlowOperating { get; set; }
        public decimal? CashFlowShareRepurchase { get; set; }
        public decimal? CashLongTerm { get; set; }
        public decimal? CashOperating { get; set; }
        public decimal? CashPaidForIncomeTaxes { get; set; }
        public decimal? CashPaidForInterest { get; set; }
        public decimal? CashRestricted { get; set; }
        public decimal? ChargeAfterTax { get; set; }
        public decimal? ChargeAfterTaxDiscontinuedOperations { get; set; }
        public decimal? ChargesAfterTaxOther { get; set; }
        public string Cik { get; set; }
        public decimal? CreditLossProvision { get; set; }
        public DateTime dataGenerationDate { get; set; }
        public decimal? DaysInAccountsPayable { get; set; }
        public decimal? DaysInInventory { get; set; }
        public decimal? DaysInRevenueDeferred { get; set; }
        public decimal? DaysRevenueOutstanding { get; set; }
        public decimal? DebtFinancial { get; set; }
        public decimal? DebtShortTerm { get; set; }
        public decimal? DepreciationAndAmortizationAccumulated { get; set; }
        public decimal? DepreciationAndAmortizationCashFlow { get; set; }
        public decimal? DividendsPreferred { get; set; }
        public decimal? DividendsPreferredRedeemableMandatorily { get; set; }
        public decimal? EarningsRetained { get; set; }
        public decimal? EbitReported { get; set; }
        public decimal? EbitdaReported { get; set; }
        public decimal? EquityShareholder { get; set; }
        public decimal? EquityShareholderOther { get; set; }
        public decimal? EquityShareholderOtherDeferredCompensation { get; set; }
        public decimal? EquityShareholderOtherEquity { get; set; }
        public decimal? EquityShareholderOtherMezzanine { get; set; }
        public decimal? Expenses { get; set; }
        public decimal? ExpensesAcquisitionMerger { get; set; }
        public decimal? ExpensesCompensation { get; set; }
        public decimal? ExpensesDepreciationAndAmortization { get; set; }
        public decimal? ExpensesDerivative { get; set; }
        public decimal? ExpensesDiscontinuedOperations { get; set; }
        public decimal? ExpensesDiscontinuedOperationsReits { get; set; }
        public decimal? ExpensesEnergy { get; set; }
        public decimal? ExpensesForeignCurrency { get; set; }
        public decimal? ExpensesInterest { get; set; }
        public decimal? ExpensesInterestFinancials { get; set; }
        public decimal? ExpensesInterestMinority { get; set; }
        public decimal? ExpensesLegalRegulatoryInsurance { get; set; }
        public decimal? ExpensesNonOperatingCompanyDefinedOther { get; set; }
        public decimal? ExpensesNonOperatingOther { get; set; }
        public decimal? ExpensesNonOperatingSubsidiaryUnconsolidated { get; set; }
        public decimal? ExpensesNonRecurringOther { get; set; }
        public decimal? ExpensesOperating { get; set; }
        public decimal? ExpensesOperatingOther { get; set; }
        public decimal? ExpensesOperatingSubsidiaryUnconsolidated { get; set; }
        public decimal? ExpensesOreo { get; set; }
        public decimal? ExpensesOreoReits { get; set; }
        public decimal? ExpensesOtherFinancing { get; set; }
        public decimal? ExpensesRestructuring { get; set; }
        public decimal? ExpensesSga { get; set; }
        public decimal? ExpensesStockCompensation { get; set; }
        public decimal? ExpensesWriteDown { get; set; }
        public decimal? Ffo { get; set; }
        public string Figi { get; set; }
        public DateTime FilingDate { get; set; }
        public string FilingType { get; set; }
        public int FiscalQuarter { get; set; }
        public int FiscalYear { get; set; }
        public decimal? GoodwillAmortizationCashFlow { get; set; }
        public decimal? GoodwillAmortizationIncomeStatement { get; set; }
        public decimal? GoodwillAndIntangiblesNetOther { get; set; }
        public decimal? GoodwillNet { get; set; }
        public decimal? IncomeFromOperations { get; set; }
        public decimal? IncomeNet { get; set; }
        public decimal? IncomeNetPerRevenue { get; set; }
        public decimal? IncomeNetPerWabso { get; set; }
        public decimal? IncomeNetPerWabsoSplitAdjusted { get; set; }
        public decimal? IncomeNetPerWabsoSplitAdjustedYoyDeltaPercent { get; set; }
        public decimal? IncomeNetPerWadso { get; set; }
        public decimal? IncomeNetPerWadsoSplitAdjusted { get; set; }
        public decimal? IncomeNetPerWadsoSplitAdjustedYoyDeltaPercent { get; set; }
        public decimal? IncomeNetPreTax { get; set; }
        public decimal? IncomeNetYoyDelta { get; set; }
        public decimal? IncomeOperating { get; set; }
        public decimal? IncomeOperatingDiscontinuedOperations { get; set; }
        public decimal? IncomeOperatingOther { get; set; }
        public decimal? IncomeOperatingSubsidiaryUnconsolidated { get; set; }
        public decimal? IncomeOperatingSubsidiaryUnconsolidatedAfterTax { get; set; }
        public decimal? IncomeTax { get; set; }
        public decimal? IncomeTaxCurrent { get; set; }
        public decimal? IncomeTaxDeferred { get; set; }
        public decimal? IncomeTaxDiscontinuedOperations { get; set; }
        public decimal? IncomeTaxOther { get; set; }
        public decimal? IncomeTaxRate { get; set; }
        public decimal? InterestMinority { get; set; }
        public decimal? Inventory { get; set; }
        public decimal? InventoryTurnover { get; set; }
        public decimal? Liabilities { get; set; }
        public decimal? LiabilitiesCurrent { get; set; }
        public decimal? LiabilitiesNonCurrentAndInterestMinorityTotal { get; set; }
        public decimal? LiabilitiesNonCurrentDebt { get; set; }
        public decimal? LiabilitiesNonCurrentDeferredCompensation { get; set; }
        public decimal? LiabilitiesNonCurrentDeferredTax { get; set; }
        public decimal? LiabilitiesNonCurrentDiscontinuedOperations { get; set; }
        public decimal? LiabilitiesNonCurrentLeasesOperating { get; set; }
        public decimal? LiabilitiesNonCurrentLongTerm { get; set; }
        public decimal? LiabilitiesNonCurrentOperatingDiscontinuedOperations { get; set; }
        public decimal? LiabilitiesNonCurrentOther { get; set; }
        public decimal? NibclDeferredCompensation { get; set; }
        public decimal? NibclDeferredTax { get; set; }
        public decimal? NibclDiscontinuedOperations { get; set; }
        public decimal? NibclLeasesOperating { get; set; }
        public decimal? NibclOther { get; set; }
        public decimal? NibclRestructuring { get; set; }
        public decimal? NibclRevenueDeferred { get; set; }
        public decimal? NibclRevenueDeferredTurnover { get; set; }
        public decimal? NibclSeparateAccounts { get; set; }
        public decimal? Oci { get; set; }
        public DateTime PeriodEndDate { get; set; }
        public decimal? PpAndENet { get; set; }
        public decimal? PricePerEarnings { get; set; }
        public decimal? PricePerEarningsPerRevenueYoyDeltaPercent { get; set; }
        public decimal? ProfitGross { get; set; }
        public decimal? ProfitGrossPerRevenue { get; set; }
        public decimal? ResearchAndDevelopmentExpense { get; set; }
        public decimal? Reserves { get; set; }
        public decimal? ReservesInventory { get; set; }
        public decimal? ReservesLifo { get; set; }
        public decimal? ReservesLoanLoss { get; set; }
        public decimal? Revenue { get; set; }
        public decimal? RevenueCostOther { get; set; }
        public decimal? RevenueIncomeInterest { get; set; }
        public decimal? RevenueOther { get; set; }
        public decimal? RevenueSubsidiaryUnconsolidated { get; set; }
        public decimal? SalesCost { get; set; }
        public decimal? SharesIssued { get; set; }
        public decimal? SharesOutstandingPeDateBs { get; set; }
        public decimal? SharesTreasury { get; set; }
        public decimal? StockCommon { get; set; }
        public decimal? StockPreferred { get; set; }
        public decimal? StockPreferredEquity { get; set; }
        public decimal? StockPreferredMezzanine { get; set; }
        public decimal? StockTreasury { get; set; }
        public string Symbol { get; set; }
        public decimal? Wabso { get; set; }
        public decimal? WabsoSplitAdjusted { get; set; }
        public decimal? Wadso { get; set; }
        public decimal? WadsoSplitAdjusted { get; set; }
        public string Id { get; set; }
        public string Key { get; set; }
        public string Subkey { get; set; }
        public long Date { get; set; }
        public decimal Updated { get; set; }
    }
}
