namespace FinanceProcessor.Core.Models
{
	public class FundamentalValuationsDto
	{
        public double AccountsPayableTurnover { get; set; }
        public double AccountsReceivableTurnover { get; set; }
        public double AltmanZScore { get; set; }
        public string AsOfDate { get; set; }
        public double AssetsToEquity { get; set; }
        public double AssetTurnover { get; set; }
        public string BbgCompositeTicker { get; set; }
        public double BookValuePerShare { get; set; }
        public double CashConversionCycle { get; set; }
        public string Cik { get; set; }
        public string CompanyName { get; set; }
        public string CompanyStatusCurrent { get; set; }
        public double CurrentRatio { get; set; }
        public string DataGenerationDate { get; set; }
        public string DataType { get; set; }
        public double DaysInAccountsPayable { get; set; }
        public double DaysInInventory { get; set; }
        public double DaysInRevenueDeferred { get; set; }
        public double DaysRevenueOutstanding { get; set; }
        public double DebtToAssets { get; set; }
        public double DebtToCapitalization { get; set; }
        public double DebtToEbitda { get; set; }
        public double DebtToEquity { get; set; }
        public double DividendPerShare { get; set; }
        public double DividendYield { get; set; }
        public double EarningsYield { get; set; }
        public double EbitdaGrowth { get; set; }
        public double EbitdaMargin { get; set; }
        public long EbitdaReported { get; set; }
        public double EbitGrowth { get; set; }
        public long EbitReported { get; set; }
        public double EbitToInterestExpense { get; set; }
        public double EbitToRevenue { get; set; }
        public long EnterpriseValue { get; set; }
        public double EvToEbit { get; set; }
        public double EvToEbitda { get; set; }
        public double EvToFcf { get; set; }
        public double EvToInvestedCapital { get; set; }
        public double EvToNopat { get; set; }
        public double EvToOcf { get; set; }
        public double EvToSales { get; set; }
        public long ExpenseOperating { get; set; }
        public double FcfYield { get; set; }
        public string Figi { get; set; }
        public string FilingDate { get; set; }
        public string FilingType { get; set; }
        public long FiscalQuarter { get; set; }
        public long FiscalYear { get; set; }
        public double FixedAssetTurnover { get; set; }
        public double FreeCashFlow { get; set; }
        public double FreeCashFlowGrowth { get; set; }
        public double FreeCashFlowToRevenue { get; set; }
        public long GoodwillTotal { get; set; }
        public double IncomeNetPerWabso { get; set; }
        public double IncomeNetPerWabsoSplitAdjusted { get; set; }
        public double IncomeNetPerWabsoSplitAdjustedYoyDeltaPercent { get; set; }
        public double IncomeNetPerWadso { get; set; }
        public double IncomeNetPerWadsoSplitAdjusted { get; set; }
        public double IncomeNetPerWadsoSplitAdjustedYoyDeltaPercent { get; set; }
        public long IncomeNetPreTax { get; set; }
        public double InterestBurden { get; set; }
        public long InterestMinority { get; set; }
        public double InventoryTurnover { get; set; }
        public long InvestedCapital { get; set; }
        public double InvestedCapitalGrowth { get; set; }
        public double InvestedCapitalTurnover { get; set; }
        public double Leverage { get; set; }
        public long MarketCapPeriodEnd { get; set; }
        public long NetDebt { get; set; }
        public double NetDebtToEbitda { get; set; }
        public double NetIncomeGrowth { get; set; }
        public double NetIncomeToRevenue { get; set; }
        public long NetWorkingCapital { get; set; }
        public double NetWorkingCapitalGrowth { get; set; }
        public double NibclRevenueDeferredTurnover { get; set; }
        public double Nopat { get; set; }
        public double NopatGrowth { get; set; }
        public double NopatMargin { get; set; }
        public double OperatingCashFlowGrowth { get; set; }
        public double OperatingCashFlowInterestCoverage { get; set; }
        public double OperatingCfToRevenue { get; set; }
        public long OperatingIncome { get; set; }
        public double OperatingIncomeToRevenue { get; set; }
        public double OperatingReturnOnAssets { get; set; }
        public string PeriodEndDate { get; set; }
        public long PpAndENet { get; set; }
        public long PreferredEquityToCapital { get; set; }
        public double PretaxIncomeMargin { get; set; }
        public double PriceAccountingPeriodEnd { get; set; }
        public string PriceDateAccountingPeriodEnd { get; set; }
        public double PriceToRevenue { get; set; }
        public double ProfitGrossToRevenue { get; set; }
        public double PToBv { get; set; }
        public double PToE { get; set; }
        public double QuickRatio { get; set; }
        public double ResearchDevelopmentToRevenue { get; set; }
        public double ReturnOnAssets { get; set; }
        public double ReturnOnEquity { get; set; }
        public double RevenueGrowth { get; set; }
        public double Roce { get; set; }
        public double Roic { get; set; }
        public long Scexhid { get; set; }
        public long Secid { get; set; }
        public double SgaToRevenue { get; set; }
        public string StockExchange { get; set; }
        public string Symbol { get; set; }
        public double TaxBurden { get; set; }
        public string Ticker { get; set; }
        public long TotalCapital { get; set; }
        public long TotalDebt { get; set; }
        public string UpdateReason { get; set; }
        public long Wabso { get; set; }
        public long WabsoSplitAdjusted { get; set; }
        public long Wadso { get; set; }
        public long WadsoSplitAdjusted { get; set; }
        public double WorkingCapitalTurnover { get; set; }
        public string Id { get; set; }
        public string Key { get; set; }
        public string Subkey { get; set; }
        public long Date { get; set; }
        public double Updated { get; set; }
    }
}
